apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuberhealthy
  namespace: kuberhealthy
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kuberhealthy
  template:
    metadata:
      labels:
        app: kuberhealthy
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
    spec:
      serviceAccountName: kuberhealthy
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: kuberhealthy
            topologyKey: kubernetes.io/hostname
      containers:
      - name: kuberhealthy
        image: docker.io/kuberhealthy/kuberhealthy:main
        imagePullPolicy: IfNotPresent
        env:
        - name: KH_LISTEN_ADDRESS
          value: ":8080"
        - name: KH_LOG_LEVEL
          value: "info"
        - name: KH_MAX_JOB_AGE
          value: ""
        - name: KH_MAX_CHECK_POD_AGE
          value: ""
        - name: KH_MAX_COMPLETED_POD_COUNT
          value: "1"
        - name: KH_MAX_ERROR_POD_COUNT
          value: "2"
        - name: KH_ERROR_POD_RETENTION_TIME
          value: "36h"
        - name: KH_PROM_SUPPRESS_ERROR_LABEL
          value: "false"
        - name: KH_PROM_ERROR_LABEL_MAX_LENGTH
          value: "0"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KH_CHECK_REPORT_URL
          value: "http://kuberhealthy.kuberhealthy.svc.cluster.local:8080"
        - name: KH_DEFAULT_RUN_INTERVAL
          value: "10m"
        - name: KH_TERMINATION_GRACE_PERIOD
          value: "5m"
        - name: KH_DEFAULT_CHECK_TIMEOUT
          value: "30s"
        - name: KH_DEFAULT_NAMESPACE
          value: "kuberhealthy"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
