apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace.yaml
  - base/deployment.yaml
  - base/podDisruptionBudget.yaml
  - base/service.yaml
  - base/healthcheck.yaml
  - base/clusterrole.yaml
  - base/serviceaccount.yaml
