apiVersion: v2
name: kuberhealthy
appVersion: v2.4.1
version: 59
home: https://comcast.github.io/kuberhealthy/
description: "An operator for synthetic test and monitoring. Works great with Prometheus."
type: application
maintainers:
  - name: integrii
    email: eric.greer@comcast.com
  - name: lolimjake
    email: jacob.martin@comcast.com
  - name: ihoegen
    email: ianhoegen@gmail.com
  - name: jonnydawg
    email: jonathan_phan@comcast.com
  - name: joshulyne
    email: joshulyne_park@comcast.com
keywords:
- kuberhealthy
- kubernetes
- operator
- monitoring
- synthetic
- testing
- comcast
- health
- prometheus
sources:
- https://github.com/Comcast/kuberhealthy
- https://github.com/Comcast/kuberhealthy/tree/master/deploy/helm/kuberhealthy
icon: https://raw.githubusercontent.com/Comcast/kuberhealthy/master/images/logo-square.png
