apiVersion: v2
name: kuberhealthy
appVersion: main
version: 1
home: https://kuberhealthy.github.io/kuberhealthy/
description: "Kuberhealthy v3 operator chart (minimal install)."
type: application
maintainers:
  - name: integrii
    email: ericgreer@gmail.com
keywords:
  - kuberhealthy
  - kubernetes
  - operator
  - monitoring
  - synthetic
  - testing
  - health
sources:
  - https://github.com/kuberhealthy/kuberhealthy
  - https://github.com/kuberhealthy/kuberhealthy/tree/main/deploy/helm/kuberhealthy
icon: https://raw.githubusercontent.com/kuberhealthy/kuberhealthy/master/images/logo-square.png
