{{- if .Values.checkReaper.enabled }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: check-reaper
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: check-reaper
              {{- if .Values.imageRegistry }}
              image: {{- .Values.imageRegistry }}/{{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
              {{- else if .Values.checkReaper.image.registry }}
              image: {{ .Values.checkReaper.image.registry }}/{{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
              {{- else }}
              image: {{ .Values.checkReaper.image.repository }}:{{ .Values.checkReaper.image.tag }}
              {{- end }}
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 10m
                  memory: 50Mi
              env:
                - name: SINGLE_NAMESPACE
                  value: ""
                - name: MAX_PODS_THRESHOLD
                  value: "4"
                - name: JOB_DELETE_TIME_DURATION
                  value: 15m
              securityContext:
                runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
                runAsUser: {{ .Values.securityContext.runAsUser }}
                allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          {{- if .Values.checkReaper.nodeSelector }}
          nodeSelector:
{{- toYaml .Values.checkReaper.nodeSelector | nindent 12 }}
          {{- end }}
          {{- if .Values.checkReaper.tolerations }}
          tolerations:
{{- toYaml .Values.checkReaper.tolerations | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          serviceAccountName: check-reaper
  concurrencyPolicy: Forbid
  {{- if .Values.checkReaper.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.checkReaper.startingDeadlineSeconds }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: check-reaper
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kuberhealthy.name" . }}-check-reaper
subjects:
  - kind: ServiceAccount
    name: check-reaper
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: check-reaper
  namespace: {{ .Release.Namespace }}
{{- end }}
