{{- if .Values.check.podStatus.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-status
spec:
  runInterval: 5m
  timeout: 15m
  podSpec:
    containers:
      - env:
          - name: SKIP_DURATION
            value: "10m"
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
{{- range $key, $value := .Values.check.podStatus.extraEnvs }}
          - name: {{ $key }}
            value: {{ $value | quote }}
{{- end }}
        image: {{ .Values.check.podStatus.image.repository }}:{{ .Values.check.podStatus.image.tag }}
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
    {{- if .Values.check.podStatus.nodeSelector }}
    nodeSelector:
{{- toYaml .Values.check.podStatus.nodeSelector | nindent 6 }}
    {{- end }}
{{- end }}
