{{- if .Values.check.podStatus.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-status
spec:
  runInterval: {{ .Values.check.podStatus.runInterval }}
  timeout: {{ .Values.check.podStatus.timeout }}
  podSpec:
    {{- if .Values.securityContext.enabled }}
    securityContext:
      runAsUser: {{ .Values.securityContext.runAsUser }}
      fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- if .Values.securityContext.seccompProfile }}
      seccompProfile:
        {{- toYaml .Values.securityContext.seccompProfile | nindent 8 }}
      {{- end }}
    {{- end}}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    containers:
      - env:
          - name: SKIP_DURATION
            value: "10m"
          {{- if not .Values.check.podStatus.allNamespaces }}
          - name: TARGET_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
{{- range $key, $value := .Values.check.podStatus.extraEnvs }}
          - name: {{ $key }}
            value: {{ $value | quote }}
{{- end }}
        {{- if .Values.imageRegistry }}
        image: "{{ .Values.imageRegistry }}/{{ .Values.check.podStatus.image.repository }}:{{ .Values.check.podStatus.image.tag }}"
        {{- else if .Values.check.podStatus.image.registry }}
        image: "{{ .Values.check.podStatus.image.registry }}/{{ .Values.check.podStatus.image.repository }}:{{ .Values.check.podStatus.image.tag }}"
        {{- end }}
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: {{ .Values.check.podStatus.resources.requests.cpu }}
            memory: {{ .Values.check.podStatus.resources.requests.memory }}
          {{- if .Values.check.podStatus.resources.limits }}
          limits:
            {{- if .Values.check.podStatus.resources.limits.cpu }}
            cpu: {{ .Values.check.podStatus.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.check.podStatus.resources.limits.memory }}
            memory: {{ .Values.check.podStatus.resources.limits.memory }}
            {{- end }}
          {{- end }}
        {{- if .Values.securityContext.enabled }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
        {{- end }}

    {{- if .Values.check.podStatus.nodeSelector }}
    nodeSelector:
{{- toYaml .Values.check.podStatus.nodeSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.check.podStatus.tolerations }}
    tolerations:
{{- toYaml .Values.check.podStatus.tolerations | nindent 6 }}
    {{- end }}
    serviceAccountName: pod-status-sa
---
{{- if .Values.check.podStatus.allNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-status-check-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-status-role
subjects:
  - kind: ServiceAccount
    name: pod-status-sa
    namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-status-role
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- if not .Values.check.podStatus.allNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-status-rb
  namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-status-role
subjects:
  - kind: ServiceAccount
    name: pod-status-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-status-role
  namespace: {{ .Values.namespace | default .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
      - list
      - watch
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-status-sa
{{- if .Values.check.podStatus.allNamespaces }}
  namespace: kuberhealthy
{{- else }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end}}
{{- end}}
