{{- if .Values.check.dnsInternal.enabled }}
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: dns-status-internal
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  runInterval: {{ .Values.check.dnsInternal.runInterval }}
  timeout: {{ .Values.check.dnsInternal.timeout }}
  podSpec:
    {{- if .Values.securityContext.enabled }}
    securityContext:
      runAsUser: {{ .Values.securityContext.runAsUser }}
      fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- if .Values.securityContext.seccompProfile }}
      seccompProfile:
        {{- toYaml .Values.securityContext.seccompProfile | nindent 8 }}
      {{- end }}
    {{- end}}
    {{- if .Values.imagePullSecrets }}
    imagePullSecrets:
      {{ toYaml .Values.imagePullSecrets | indent 2 }}
    {{- end }}
    containers:
      - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
{{- range $key, $value := .Values.check.dnsInternal.extraEnvs }}
          - name: {{ $key }}
            value: {{ $value | quote }}
{{- end }}
        {{- if .Values.imageRegistry }}
        image: "{{ .Values.imageRegistry }}/{{ .Values.check.dnsInternal.image.repository }}:{{ .Values.check.dnsInternal.image.tag }}"
        {{- else if .Values.check.dnsInternal.image.registry }}
        image: "{{ .Values.check.dnsInternal.image.registry }}/{{ .Values.check.dnsInternal.image.repository }}:{{ .Values.check.dnsInternal.image.tag }}"
        {{- end }}
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: {{ .Values.check.dnsInternal.resources.requests.cpu }}
            memory: {{ .Values.check.dnsInternal.resources.requests.memory }}
          {{- if .Values.check.dnsInternal.resources.limits }}
          limits:
            {{- if .Values.check.dnsInternal.resources.limits.cpu }}
            cpu: {{ .Values.check.dnsInternal.resources.limits.cpu }}
            {{- end }}
            {{- if .Values.check.dnsInternal.resources.limits.memory }}
            memory: {{ .Values.check.dnsInternal.resources.limits.memory }}
            {{- end }}
          {{- end }}
        {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
        {{- end }}
    {{- if .Values.check.dnsInternal.nodeSelector }}
    nodeSelector:
{{- toYaml .Values.check.dnsInternal.nodeSelector | nindent 6 }}
    {{- end }}
    {{- if .Values.check.dnsInternal.tolerations }}
    tolerations:
{{- toYaml .Values.check.dnsInternal.tolerations | nindent 6 }}
    {{- end }}
    serviceAccountName: dns-internal-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-internal-service-cr
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-internal-service-crb
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: dns-internal-service-cr
subjects:
  - kind: ServiceAccount
    name: dns-internal-sa
    namespace: {{ .Values.namespace | default .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-internal-sa
  namespace: {{ .Values.namespace | default .Release.Namespace }}
{{- end }}
